<robot name="my_laser" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- 雷达支架 -->
    <xacro:property name="support_length" value="0.15" />
    <xacro:property name="support_radius" value="0.01" />
    <xacro:property name="support_x" value="0.05" />
    <xacro:property name="support_y" value="0.0" />
    <xacro:property name="support_z" value="${base_link_length / 2 + support_length / 2}" />
    <xacro:property name="support_m" value="0.02" />

    <link name="support_front">
        <visual>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="red">
                <color rgba="0.8 0.2 0.0 0.8" />
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_length}" />
            </geometry>
        </collision>
        <xacro:cylinder_inertial_matrix m="${support_m}" r="${support_radius}" h="${support_length}" />
    </link>

    <joint name="support_front2base_link" type="fixed">
        <parent link="base_link" />
        <child link="support_front" />
        <origin xyz="${support_x} ${support_y} ${support_z}" />
    </joint>

    <!-- 雷达属性 -->
    <xacro:property name="laser_length" value="0.03" />
    <xacro:property name="laser_radius" value="0.02" />
    <xacro:property name="laser_x" value="0.02" />
    <xacro:property name="laser_y" value="0.0" />
    <xacro:property name="laser_z" value="${support_length / 2 + laser_length / 2}" />
    <xacro:property name="laser_m" value="0.1" />

    <link name="laser_front">
        <visual>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}" />
           </geometry>
            <origin xyz="0.0 0.0 0" rpy="0.0 0.0 0.0" />
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}" />
            </geometry>
        </collision>
        <xacro:cylinder_inertial_matrix m="${laser_m}" r="${laser_radius}" h="${laser_length}" />
    </link>

    <joint name="laser_front2support" type="fixed">
        <parent link="support_front" />
        <child link="laser_front" />
        <origin xyz="${laser_x} ${laser_y} ${laser_z}" />
    </joint>
</robot>
