<robot name="my_laser_rear" xmlns:xacro="http://wiki.ros.org/xacro">
  <!-- 后雷达支架 -->
  <xacro:property name="support_rear_length" value="0.15" />
  <xacro:property name="support_rear_radius" value="0.01" />
  <xacro:property name="support_rear_x" value="-0.05" /> 
  <xacro:property name="support_rear_y" value="0.0" />
  <xacro:property name="support_rear_z" value="${base_link_length / 2 + support_rear_length / 2}" />
  <xacro:property name="support_rear_m" value="0.02" />

  <link name="support_rear">
    <visual>
      <geometry>
        <cylinder radius="${support_rear_radius}" length="${support_rear_length}" />
      </geometry>
      <origin xyz="0.0 0.0 0" rpy="0.0 0.0 0.0" />
      <material name="blue">
        <color rgba="0.2 0.2 0.8 0.8" />
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${support_rear_radius}" length="${support_rear_length}" />
      </geometry>
    </collision>
    <xacro:cylinder_inertial_matrix m="${support_rear_m}" r="${support_rear_radius}" h="${support_rear_length}" />
  </link>

  <joint name="support_rear2base_link" type="fixed">
    <parent link="base_link" />
    <child link="support_rear" />
    <origin xyz="${support_rear_x} ${support_rear_y} ${support_rear_z}" rpy="0 0 3.14159" />
  </joint>

  <!-- 后雷达属性 -->
  <xacro:property name="laser_rear_length" value="0.03" />
  <xacro:property name="laser_rear_radius" value="0.02" />
  <xacro:property name="laser_rear_x" value="0.02" />
  <xacro:property name="laser_rear_y" value="0.0" />
  <xacro:property name="laser_rear_z" value="${support_rear_length / 2 + laser_rear_length / 2}" />
  <xacro:property name="laser_rear_m" value="0.1" />

  <link name="laser_rear">
    <visual>
      <geometry>
        <cylinder radius="${laser_rear_radius}" length="${laser_rear_length}" />
      </geometry>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <material name="silver" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${laser_rear_radius}" length="${laser_rear_length}" />
      </geometry>
    </collision>
    <xacro:cylinder_inertial_matrix m="${laser_rear_m}" r="${laser_rear_radius}" h="${laser_rear_length}" />
  </link>

  <joint name="laser_rear2support_rear" type="fixed">
    <parent link="support_rear" />
    <child link="laser_rear" />
    <origin xyz="${laser_rear_x} ${laser_rear_y} ${laser_rear_z}" />
  </joint>
</robot>
